

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: 1
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: IMAGE_SAMPLE
        ports:
        - containerPort: 8080
       
